// Regenerate supabase/seed.sql from the canonical data files:
//   src/data/menu.ts   (food categories, MENU_DATA)
//   src/data/drinks.ts (drinks categories, DRINKS_DATA)
//
// Drinks categories are prefixed `drinks-` so the food menu (FullMenu) can
// exclude them and DrinksMenu can render them separately.
//
// Usage:  node scripts/gen-seed.mjs
// After running, paste supabase/seed.sql into the Supabase SQL Editor (or run
// it via the CLI) to load the menu into the database.

import { readFileSync, writeFileSync } from "node:fs";

// Extract an exported array literal (e.g. `export const MENU_DATA = [ ... ]`)
// from a .ts file without compiling — the literal is plain JS (no type syntax
// inside the array), so we slice the balanced brackets and eval it.
function extractArray(file, varName) {
  const src = readFileSync(file, "utf8");
  const decl = src.indexOf(varName);
  if (decl === -1) throw new Error(`${varName} not found in ${file}`);
  const eq = src.indexOf("[", src.indexOf("=", decl));
  let depth = 0, end = -1;
  for (let i = eq; i < src.length; i++) {
    const c = src[i];
    if (c === "[") depth++;
    else if (c === "]") { depth--; if (depth === 0) { end = i; break; } }
  }
  return eval(src.slice(eq, end + 1));
}

const FOOD = extractArray("src/data/menu.ts", "MENU_DATA");
const DRINKS = extractArray("src/data/drinks.ts", "DRINKS_DATA");
const ALL = [...FOOD, ...DRINKS];

const esc = (s) => String(s).replace(/'/g, "''");

let out = "";
out += "-- Full menu seed (food + drinks) — GENERATED by scripts/gen-seed.mjs.\n";
out += "-- Source of truth: src/data/menu.ts (food) and src/data/drinks.ts (drinks).\n";
out += "-- Do not edit by hand; re-run `node scripts/gen-seed.mjs` instead.\n";
out += "-- Run this in the Supabase SQL Editor AFTER 0001_init.sql.\n";
out += "-- Safe to re-run: it clears the menu tables first, then re-inserts.\n\n";
out += "truncate table menu_items, menu_categories restart identity cascade;\n\n";

out += "insert into menu_categories (id, title, sort_order) values\n";
out += ALL.map((c, i) => `  ('${esc(c.id)}', '${esc(c.title)}', ${i})`).join(",\n") + ";\n\n";

out += "insert into menu_items (category_id, name, price, description, sort_order) values\n";
const rows = [];
for (const c of ALL) {
  c.items.forEach((it, idx) => {
    const desc = it.description ? `'${esc(it.description)}'` : "null";
    rows.push(`  ('${esc(c.id)}','${esc(it.name)}','${esc(it.price)}',${desc},${idx})`);
  });
}
out += rows.join(",\n") + ";\n";

writeFileSync("supabase/seed.sql", out);
console.log(
  `Wrote supabase/seed.sql: ${ALL.length} categories ` +
  `(${FOOD.length} food + ${DRINKS.length} drinks), ${rows.length} items`
);
